"""Create a public preview image showing outputs generated by favar."""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

try:
    from favar import FAVAR
except ModuleNotFoundError:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    from favar import FAVAR


def simulate_public_example(
    nobs: int = 180,
    nseries: int = 48,
    k_factors: int = 2,
    n_slow: int = 26,
    seed: int = 2026,
):
    rng = np.random.default_rng(seed)
    state_dim = k_factors + 1
    transition = np.array(
        [
            [0.60, 0.12, -0.04],
            [0.08, 0.52, 0.10],
            [0.18, 0.22, 0.58],
        ]
    )
    shocks = np.array(
        [
            [0.70, 0.00, 0.00],
            [0.20, 0.55, 0.00],
            [-0.10, 0.18, 0.45],
        ]
    )
    burn = 160
    states = np.zeros((nobs + burn, state_dim))
    for t in range(1, len(states)):
        states[t] = transition @ states[t - 1] + shocks @ rng.normal(size=state_dim)
    states = states[burn:]

    factors = states[:, :k_factors]
    policy = states[:, 2]
    factor_loadings = rng.normal(size=(nseries, k_factors))
    policy_loadings = rng.normal(scale=0.5, size=nseries)
    policy_loadings[:n_slow] = 0.0

    x = (
        factors @ factor_loadings.T
        + np.outer(policy, policy_loadings)
        + rng.normal(scale=0.45, size=(nobs, nseries))
    )
    index = pd.period_range("2010-01", periods=nobs, freq="M")
    X = pd.DataFrame(
        x,
        index=index,
        columns=[f"indicator_{i + 1:02d}" for i in range(nseries)],
    )
    Y = pd.DataFrame(
        {
            "Activity": 0.85 * factors[:, 0] + 0.10 * factors[:, 1] + rng.normal(scale=0.15, size=nobs),
            "Inflation": 0.25 * factors[:, 0] + 0.65 * factors[:, 1] + rng.normal(scale=0.15, size=nobs),
            "Policy Rate": policy + rng.normal(scale=0.08, size=nobs),
        },
        index=index,
    )
    slow_columns = list(X.columns[:n_slow])
    return X, Y, slow_columns


def minmax_by_column(values: pd.DataFrame) -> pd.DataFrame:
    out = values.copy()
    for col in out.columns:
        series = out[col]
        span = series.max() - series.min()
        out[col] = 0.5 if np.isclose(span, 0.0) else (series - series.min()) / span
    return out


def create_preview(output_path: Path):
    X, Y, slow_columns = simulate_public_example()
    model = FAVAR(
        X=X,
        Y=Y,
        policy_var="Policy Rate",
        k_factors=2,
        slow_columns=slow_columns,
        standardize=True,
    )
    order_selection = model.select_order(maxlags=6)
    results = model.fit(lags=2)

    forecast = results.forecast(steps=18, confidence_level=0.90)
    irf = results.impulse_response(periods=36, impulse_size=0.25, include_factors=False)
    panel_irf = results.panel_impulse_response(
        periods=30,
        impulse_size=0.25,
        columns=["indicator_01", "indicator_12", "indicator_36"],
        scale="std",
    )
    order_frame = order_selection.to_frame()
    order_norm = minmax_by_column(order_frame[["AIC", "BIC", "FPE", "HQIC"]])

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "axes.titlesize": 13,
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )
    fig = plt.figure(figsize=(14, 8), dpi=160, facecolor="#f7f8fb")
    grid = fig.add_gridspec(
        3,
        4,
        height_ratios=[0.42, 1.0, 1.0],
        hspace=0.55,
        wspace=0.40,
    )

    header = fig.add_subplot(grid[0, :])
    header.axis("off")
    header.text(
        0.00,
        0.78,
        "Factor-Augmented Vector Autoregression (FAVAR)",
        fontsize=24,
        fontweight="bold",
        color="#172033",
        va="center",
    )
    header.text(
        0.00,
        0.35,
        "A Python package for high-dimensional macroeconomic forecasting, policy shocks, and panel impulse responses",
        fontsize=12.5,
        color="#46556f",
        va="center",
    )
    header.text(
        0.99,
        0.58,
        "pip install favar",
        fontsize=13,
        color="white",
        va="center",
        ha="right",
        bbox={"boxstyle": "round,pad=0.45,rounding_size=0.15", "facecolor": "#1f6feb", "edgecolor": "none"},
    )

    ax_fc = fig.add_subplot(grid[1, :2])
    hist = Y["Activity"].iloc[-42:]
    x_hist = np.arange(len(hist))
    x_fc = np.arange(len(hist), len(hist) + len(forecast))
    ax_fc.plot(x_hist, hist.to_numpy(), color="#253858", linewidth=2.2, label="observed")
    ax_fc.plot(x_fc, forecast["Activity"], color="#1f6feb", linewidth=2.4, label="forecast")
    ax_fc.fill_between(
        x_fc,
        forecast["Activity_lower"],
        forecast["Activity_upper"],
        color="#1f6feb",
        alpha=0.16,
        label="90% interval",
    )
    ax_fc.axvline(len(hist) - 0.5, color="#8a94a6", linewidth=1.2, linestyle="--")
    ax_fc.set_title("Forecasts with confidence intervals")
    ax_fc.set_xlabel("months")
    ax_fc.set_ylabel("Activity")
    ax_fc.legend(loc="upper left", frameon=False, ncol=3)
    ax_fc.grid(color="#dbe1ea", linewidth=0.8)

    ax_irf = fig.add_subplot(grid[1, 2:])
    for col, color in zip(irf.columns, ["#1f6feb", "#d97706", "#2f9e44"]):
        ax_irf.plot(irf.index, irf[col], linewidth=2.3, label=col, color=color)
    ax_irf.axhline(0, color="#253858", linewidth=0.9)
    ax_irf.set_title("Orthogonalized impulse responses")
    ax_irf.set_xlabel("periods after policy shock")
    ax_irf.set_ylabel("response")
    ax_irf.legend(loc="upper right", frameon=False)
    ax_irf.grid(color="#dbe1ea", linewidth=0.8)

    ax_panel = fig.add_subplot(grid[2, :2])
    for col, color in zip(panel_irf.columns, ["#6f42c1", "#0f766e", "#c2410c"]):
        ax_panel.plot(panel_irf.index, panel_irf[col], linewidth=2.2, label=col, color=color)
    ax_panel.axhline(0, color="#253858", linewidth=0.9)
    ax_panel.set_title("Panel-projected responses for selected indicators")
    ax_panel.set_xlabel("periods after policy shock")
    ax_panel.set_ylabel("standardized response")
    ax_panel.legend(loc="upper right", frameon=False)
    ax_panel.grid(color="#dbe1ea", linewidth=0.8)

    ax_order = fig.add_subplot(grid[2, 2])
    image = ax_order.imshow(order_norm.to_numpy(), aspect="auto", cmap="viridis_r")
    ax_order.set_title("Lag-order selection")
    ax_order.set_xticks(np.arange(order_norm.shape[1]), order_norm.columns)
    ax_order.set_yticks(np.arange(order_norm.shape[0]), order_norm.index)
    ax_order.set_ylabel("lag")
    for i, lag in enumerate(order_norm.index):
        for j, col in enumerate(order_norm.columns):
            selected = lag == order_selection.selected_orders[col.lower()]
            text = "*" if selected else ""
            ax_order.text(j, i, text, ha="center", va="center", color="white", fontsize=18, fontweight="bold")
    fig.colorbar(image, ax=ax_order, fraction=0.046, pad=0.04, label="relative criterion")

    ax_summary = fig.add_subplot(grid[2, 3])
    ax_summary.axis("off")
    rows = [
        ("Model", "FAVAR"),
        ("Factors", str(results.K)),
        ("Panel series", str(results.N)),
        ("Observed Y", str(results.M)),
        ("Policy variable", results.policy_var),
        ("VAR lags", str(results.k_ar)),
        ("Stable", str(results.is_stable())),
    ]
    ax_summary.set_title("Model summary")
    y = 0.90
    for label, value in rows:
        ax_summary.text(0.02, y, label, color="#667085", fontsize=10, va="center")
        ax_summary.text(0.98, y, value, color="#172033", fontsize=10, va="center", ha="right", fontweight="bold")
        y -= 0.11
    ax_summary.text(
        0.02,
        0.02,
        "summary()  forecast()  impulse_response()",
        fontsize=8.6,
        color="#475467",
    )

    for ax in [ax_fc, ax_irf, ax_panel, ax_order, ax_summary]:
        ax.set_facecolor("white")
        for spine in ax.spines.values():
            spine.set_color("#d0d7e2")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)


if __name__ == "__main__":
    output = Path(__file__).resolve().parents[1] / "docs" / "assets" / "favar-public-preview.png"
    create_preview(output)
    print(output)
